name = "Vanilla Plus"
author = "Kiki"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8927d6f49e53e7a8947efda9b4541ee61d44049c19d683947a33f222236feb1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
