name = "Vanilla Plus"
author = "Kiki"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b875d8946ec5599a19d604cdc02ea0cc3bfc1d19bb85eac6d1b004d3bc51bcaa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
