name = "Vanilla Plus"
author = "Kiki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "421902caffcb800cd33ee57d2cd2581cf260d2fa2fca592954a4b0aaed97d0dc"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
