modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Glue for the Vanilla Plus pack.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="vanillaplus_tweaks.mixins.json"

[[dependencies.${mod_id}]]
    modId="sable"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sereneseasons"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
